### ISSUE TITLE
도메인 설계

### ISSUE THREAD

**Issue by sGOM** [shoushou-backend-developers/kiosk-project#4]
키오스크 도메인 설계 
* [x] 도메인 ERD 다이어그램 작성
* [x] 자바 클래스로 도메인 간단하게 생성
    * [x] 커피 
    * [x] 오더
    * [x] 커피오더
    * [x] 커피오더옵션
    * [x] 옵션

**Comment by sGOM** [comment]
도메인 ERD 다이어그램 작성 링크
* https://www.erdcloud.com/d/Ajnebm4KypQDMbMwq

**Comment by Baeyonghyeon** [comment]
권한이 팀으로 설정되어 있어 이미지 캡쳐해 올립니다.


![Image](https://user-images.githubusercontent.com/65753912/205902172-6e794348-4fc5-42c3-9e84-e530583061e5.png)

**Comment by ckaanf** [comment]
확인했습니다 👍
