### ISSUE TITLE
kiosk 뷰 설계

### ISSUE THREAD

**Issue by Baeyonghyeon** [shoushou-backend-developers/kiosk-project#8]
서비스 뷰를 설계 한다.

**Comment by Baeyonghyeon** [comment]
- [kiosk view 링크](https://docs.google.com/presentation/d/1ORGlS0QbAaIutHUcfIu9fnF8heY9m_Oduom9SxrfDg4/edit#slide=id.g1a7c71bd43f_4_75)

**Comment by ckaanf** [comment]
확인했습니다 👍
